# Generated by Django 2.2.7 on 2020-02-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('categorie', models.CharField(max_length=255)),
                ('url_article', models.CharField(max_length=255)),
                ('continent', models.CharField(max_length=50)),
                ('image_min', models.CharField(max_length=255)),
                ('image_max', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('contenu', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_upd', models.DateTimeField(auto_now=True)),
                ('statut', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('categorie', models.CharField(max_length=255)),
                ('url_article', models.CharField(max_length=255)),
                ('continent', models.CharField(max_length=50)),
            ],
        ),
    ]
