# Generated by Django 2.2.7 on 2020-02-17 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lebabnet', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categorie',
        ),
        migrations.RemoveField(
            model_name='article',
            name='continent',
        ),
    ]
